version: "3"
services:

  # Discovery service
  discovery-service:
    image: birelian/discovery-service:1.0
    ports:
      - "8761:8761"
    environment:
      - "SPRING_PROFILES_ACTIVE=DOCKER"
    networks:
      - microservices-network

  # Config service
  config-service:
    depends_on:
      - discovery-service
    image: birelian/config-service:1.0
    ports:
      - "8888:8888"
    environment:
      - "SPRING_PROFILES_ACTIVE=DOCKER"
    networks:
      - microservices-network

networks:
  microservices-network:
