spring:
  application:
    name: api-gateway

server:
  port: 8000

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: DOCKER

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

  instance:
    preferIpAddress: true