spring:
  application:
    name: greeting-service

server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: "*"

greeting: Hello!!

---

spring:
  profiles: DOCKER

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

  instance:
    preferIpAddress: true